version: "3.5"

services:
  db_postgres:
    container_name: "db_boilerplate"
    image: "postgres:14.2-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
