GET http://localhost:3000/

### 


POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "e@salah.com",
    "name": "admin",
    "password": "123456"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "email@emailll.com",
    "password": "adminmmm"
}
###

GET http://localhost:3000/hidden
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsIiwiaWF0IjoxNjk3MjgyODI5fQ.wXJ7pZW0I-KCnaLnjaNr_KRBseKTu0ovSt9wqDDlq1I
Content-Type: application/json


###
POST http://localhost:3000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQGVtYWFpbC5zcyIsImlhdCI6MTY5NzM4Mjg2OX0.rtwW9JKuDrjUP7aUrOUEPsIHwwjpYL--UcpN3h9xcSg"
}

###

POST http://localhost:3000/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiZW1haWxAZW1hYWlsLnNzIiwiaWF0IjoxNjk3MzgyODY5fSwiaWF0IjoxNjk3NDk0MjUxLCJleHAiOjE2OTc0OTUxNTF9.3y_u1GN2cPPZy-t2_0nMDHzKGLSlX0DZfe6xlH4i5TA

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJhZG1pbiIsImVtYWlsIjoiZUBzYWxhaC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQ2bUNxaklpWjJOdXh3OUR0M3dWaHB1TnFHSllESGVuV3Npd1o5d2wvUlEyblc0anlLaDBueSIsImlkIjoyLCJyYXRpbmciOjB9LCJpYXQiOjE3MTM1MTYzMTAsImV4cCI6MTcxMzUxNzIxMH0.JzzPZq_fKhu6YjrEoLKTJI5otXVerlkYy71k_xxe2bk"
}